# Generated by Django 3.1.4 on 2021-01-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDrive', models.CharField(max_length=200)),
                ('weight', models.PositiveIntegerField(max_length=30)),
                ('price', models.PositiveIntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEngine', models.CharField(max_length=200)),
                ('weight', models.PositiveIntegerField(max_length=30)),
                ('price', models.PositiveIntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTransmission', models.CharField(max_length=200)),
                ('weight', models.PositiveIntegerField(max_length=30)),
                ('price', models.PositiveIntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModel', models.CharField(max_length=200)),
                ('configuration', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='server.configuration')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='drive',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='server.drives'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='engine',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='server.engines'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='transmission',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='server.transmissions'),
        ),
    ]
