# Generated by Django 3.1.5 on 2021-01-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210105_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='configuration',
        ),
        migrations.AddField(
            model_name='configuration',
            name='model',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='server.models'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drives',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='drives',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='engines',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='engines',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transmissions',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transmissions',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
