# Generated by Django 3.1.5 on 2021-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210108_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
