# Generated by Django 3.1.5 on 2021-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_configuration_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='price',
        ),
        migrations.AddField(
            model_name='configuration',
            name='suma',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
