# Generated by Django 3.1.5 on 2021-01-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210108_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='suma',
            new_name='suma1',
        ),
    ]
