# Generated by Django 3.1.5 on 2021-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210108_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='suma1',
        ),
    ]
